// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/person6/person6.proto

package person6

import (
	fmt "fmt"
	_ "github.com/arteev/proto-go-setter"
	ext "github.com/arteev/proto-go-setter/example/ext"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d5e3e2af9f0a0a, []int{0}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Person6 struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                 *Role    `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Tags                 *ext.Tag `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person6) Reset()         { *m = Person6{} }
func (m *Person6) String() string { return proto.CompactTextString(m) }
func (*Person6) ProtoMessage()    {}
func (*Person6) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d5e3e2af9f0a0a, []int{1}
}

func (m *Person6) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person6.Unmarshal(m, b)
}
func (m *Person6) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person6.Marshal(b, m, deterministic)
}
func (m *Person6) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person6.Merge(m, src)
}
func (m *Person6) XXX_Size() int {
	return xxx_messageInfo_Person6.Size(m)
}
func (m *Person6) XXX_DiscardUnknown() {
	xxx_messageInfo_Person6.DiscardUnknown(m)
}

var xxx_messageInfo_Person6 proto.InternalMessageInfo

func (m *Person6) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person6) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person6) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Person6) GetTags() *ext.Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Role)(nil), "person6.Role")
	proto.RegisterType((*Person6)(nil), "person6.Person6")
}

func init() { proto.RegisterFile("example/person6/person6.proto", fileDescriptor_f6d5e3e2af9f0a0a) }

var fileDescriptor_f6d5e3e2af9f0a0a = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0x33, 0x83, 0xd1, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae, 0x94, 0x5e, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e,
	0x72, 0x7e, 0xae, 0x7e, 0x62, 0x51, 0x49, 0x6a, 0x6a, 0x99, 0x3e, 0x58, 0x85, 0x6e, 0x7a, 0xbe,
	0x6e, 0x71, 0x6a, 0x49, 0x49, 0x6a, 0x91, 0x3e, 0x84, 0x82, 0x68, 0x94, 0x32, 0x27, 0xac, 0x1e,
	0x66, 0x73, 0x6a, 0x45, 0x09, 0x08, 0x43, 0x34, 0x2a, 0x69, 0x71, 0xb1, 0x04, 0xe5, 0xe7, 0xa4,
	0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6,
	0x08, 0x09, 0x71, 0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x4a, 0x0d, 0x8c, 0x5c, 0xec, 0x01, 0x10, 0x07, 0x62, 0xa8, 0x97, 0xe0, 0x62, 0xc9, 0x83,
	0xab, 0x77, 0x62, 0xf9, 0xf0, 0x4b, 0x9b, 0x31, 0x08, 0x2c, 0x22, 0xa4, 0xce, 0xc5, 0x52, 0x94,
	0x9f, 0x93, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x6d, 0xc4, 0xab, 0x07, 0xf3, 0x31, 0xc8, 0x5a,
	0x98, 0x42, 0x90, 0x02, 0x21, 0x25, 0x2e, 0x96, 0x92, 0xc4, 0xf4, 0x62, 0x09, 0x16, 0xb0, 0x42,
	0x0e, 0x3d, 0x90, 0x23, 0x43, 0x12, 0xd3, 0x61, 0x6a, 0x40, 0x72, 0x4e, 0x9c, 0x51, 0xb0, 0x20,
	0x4a, 0x62, 0x03, 0x7b, 0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x3d, 0x35, 0xce, 0x53,
	0x01, 0x00, 0x00,
}
