// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/person6/person6.proto

package person6

import (
	fmt "fmt"
	_ "github.com/arteev/proto-go-setter"
	ext "github.com/arteev/proto-go-setter/example/ext" //fixed
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (t *Person6) SetName(name string) {
	t.Name = name
}

func (t *Person6) SetRole(role *Role) {
	t.Role = role
}

func (t *Person6) SetTags(tags *ext.Tag) {
	t.Tags = tags
}
